language: c

dist: xenial

compiler:
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install pkg-config libusb-1.0-0-dev -qq
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
