/**
 * @file ml_errors.h
 * @brief All errors used in the library. 
 * @author Travis Lane
 * @version 0.0.1
 * @date 2013-12-14
 */

#ifndef ML_ERRORS_H
#define ML_ERRORS_H

typedef enum ml_error_codes {
  ML_OK,
  ML_NOT_IMPLEMENTED,
  ML_TEST_ERROR,
  ML_LIBRARY_ALREADY_INIT,
  ML_LIBRARY_NOT_INIT,
  ML_CONTROL_ALREADY_INIT,
  ML_CONTROL_ALREADY_NULL, 
  ML_CONTROL_WAS_NULL,
  ML_CONTROL_FREE_NULL,
  ML_CONTROL_ARR_NULL,
  ML_LIBUSB_INIT_FAILED,
  ML_INVALID_POLL_RATE,
  ML_FAILED_POLL_START,
  ML_NULL_LAUNCHER,
  ML_POSITION_WAS_NOT_NULL,
  ML_POSITION_WAS_NULL,
  ML_INDEX_OUT_OF_BOUNDS,
  ML_COUNT_ZERO,
  ML_NOT_FOUND,
  ML_ARRAY_NOT_NULL,
  ML_ARRAY_WAS_NULL,
  ML_ALLOC_FAILED,
  ML_LAUNCHER_ARRAY_INCONSISTENT,
  ML_NULL_POINTER,
  ML_NO_LAUNCHERS
} ml_error_codes;

#endif
